name: Java CI

on:
  push:
    branches:
      - main  # Измени на имя ветки, если нужно
  pull_request:
    branches:
      - main  # Измени на имя ветки, если нужно

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Измени на нужную версию JDK

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
